title: Rutvik Patel's Blog
description: I use this blog to write about things that interest me.
url: "https://heyrutvik.github.io"
twitter_username: heyrutvik
github_username: heyrutvik

# Build settings
theme: minima
plugins:
  - jekyll-feed
